# Generated by Django 4.2.2 on 2023-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mood_text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='smilar_movie',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
