# Generated by Django 4.2.2 on 2023-06-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_feedback_mood_text_feedback_smilar_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.BooleanField(default=False),
        ),
    ]
